import type {  GetStaticProps  } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {MenuFood,FoodList} from '../components/menu/interfaceMenu'
import ShowMenu from '../components/menu/showMenu'
import Modal from '../components/transitions/dialogFull'
import { useState } from 'react';

const Menu = (props:MenuFood) => {
    
  const [open, setOpen] = useState<boolean>(false);
  const [listFull, setListFull] = useState<FoodList>({list: props.entradas, name: "Entradas"});

  return (
    <div className={styles.container}>
      <Head>
        <title>Develog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <ShowMenu list={props.entradas} name="Entradas" setOpen={setOpen} setListFull={setListFull}/>
        <ShowMenu list={props.ensaladas} name="Ensaladas" setOpen={setOpen} setListFull={setListFull}/>
        <ShowMenu list={props.sandwichs} name="Sandwichs" setOpen={setOpen} setListFull={setListFull}/>
        <ShowMenu list={props.fondo} name="Fondo" setOpen={setOpen} setListFull={setListFull}/>
        <ShowMenu list={props.agregados} name="Agregados" setOpen={setOpen} setListFull={setListFull}/>
        <ShowMenu list={props.postres} name="Postres" setOpen={setOpen} setListFull={setListFull}/>
        <ShowMenu list={props.jugosBebidas} name="Jugos Bebidas" setOpen={setOpen} setListFull={setListFull}/>

        
        <Modal 
            listFull={listFull} 
            open={open} 
            setOpen={setOpen}
        />
      </main>
    </div>
  )
}



// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export const getStaticProps: GetStaticProps = async (context) => {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://maf2qxs1f6.execute-api.us-east-1.amazonaws.com/prod/api/menus')
  const posts = await res.json();

  const entradas = posts.entradas;
  const ensaladas = posts.ensaladas;
  const sandwichs = posts.sandwichs;
  const fondo = posts.fondo;
  const agregados = posts.agregados;
  const postres = posts.postres;
  const jugosBebidas = posts["jugos-bebidas"];

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props:{entradas: entradas,
           ensaladas: ensaladas,
           sandwichs: sandwichs,
           fondo: fondo,
           agregados: agregados,
           postres: postres,
           jugosBebidas: jugosBebidas}
  }
}

export default Menu
